### ISSUE TITLE
Using this with no credentials

### ISSUE THREAD

**Issue by jhylton** [R-Vision/wmi-client#12]
Hello,

Library looks really promising. I will want to use on both linux and windows, however this will run on the machine locally in an administrator context so I don't want to pass username and password in the script, just use in the current administrator context. Is there a way to run this without credentials? Not setting the credentials i get user is undefined.

thanks!

**Comment by jhylton** [comment]
I was able to update this in the username.js file that is stated in fix#5, just npm doesn't have this fix. 

thanks!

**Comment by NAlexandrov** [comment]
Hello. I published 0.5.0 version in npm now.

**Comment by jhylton** [comment]
Many thanks!

I’ll pull the latest version now ☺

-Jonathan
